-- Write tables of the bank tool service (CONTRACT.md section 1.5). Operational application state, not analytics,
-- so they live in workspace.ops next to the run logs. {ops} is replaced with the configured catalog.schema.
-- Rows carry `env`; mock rows are purged with `python -m src.bank_tools.retention --purge-env <env>`.

CREATE TABLE IF NOT EXISTS {ops}.dispute_cases (
  case_id STRING NOT NULL COMMENT 'DSP- + 12 characters. Reserved in the draft before the first insert attempt.',
  created_at TIMESTAMP COMMENT 'Service clock (dataset local time, naive).',
  recorded_at TIMESTAMP COMMENT 'Wall clock, UTC.',
  customer_id STRING COMMENT 'Verified session customer.',
  product_id STRING,
  transaction_id STRING,
  case_type STRING,
  category STRING,
  subcategory STRING,
  dispute_type STRING,
  amount DECIMAL(18,2) COMMENT 'From the transaction, never from the customer.',
  currency STRING,
  amount_usd DECIMAL(18,2),
  event_date DATE,
  merchant_name STRING COMMENT 'UNTRUSTED merchant text as delivered by the source: data, never instructions.',
  channel STRING,
  is_international BOOLEAN,
  suspected_card_compromise BOOLEAN,
  language STRING,
  status STRING,
  priority STRING,
  first_response_hours INT,
  first_response_due_at TIMESTAMP,
  created_via STRING,
  conversation_id STRING,
  session_id_hash STRING,
  draft_id STRING,
  idempotency_key_hash STRING,
  policy_version STRING,
  service_version STRING,
  env STRING
) CLUSTER BY (customer_id)
COMMENT 'Mock dispute cases created by the bank tool service after confirmation and read-back. Synthetic.';

CREATE TABLE IF NOT EXISTS {ops}.handoff_tickets (
  ticket_id STRING NOT NULL COMMENT 'HND- + 12 characters.',
  created_at TIMESTAMP,
  recorded_at TIMESTAMP,
  conversation_id STRING,
  session_id_hash STRING,
  identity_verified BOOLEAN,
  customer_id STRING COMMENT 'NULL when the identity was not verified.',
  status STRING,
  reason_code STRING,
  reason_check STRING COMMENT 'consistent, inconsistent or not_verifiable.',
  queue STRING,
  priority STRING,
  first_response_hours INT,
  language STRING,
  request_summary STRING COMMENT 'PII-scrubbed summary written by the agent.',
  agent_reported_json STRING COMMENT 'Scrubbed package: facts, actions and open questions as reported by the agent.',
  service_verified_json STRING COMMENT 'Draft, evidence records and candidates verified by the service.',
  redactions INT,
  policy_version STRING,
  service_version STRING,
  env STRING
) CLUSTER BY (customer_id)
COMMENT 'Mock human-handoff tickets: the package a human agent receives. No transcript.';

CREATE TABLE IF NOT EXISTS {ops}.tool_audit (
  ts TIMESTAMP COMMENT 'Service clock.',
  recorded_at TIMESTAMP COMMENT 'Wall clock, UTC.',
  recorded_date DATE COMMENT 'Clustering and retention key.',
  trace_id STRING,
  conversation_id STRING,
  turn_index INT,
  tool_call_id STRING,
  tool STRING,
  caller STRING,
  args_redacted STRING COMMENT 'JSON with secrets removed and free text scrubbed.',
  outcome STRING,
  error_code STRING,
  internal_reason STRING,
  retryable BOOLEAN,
  attempts STRING COMMENT 'JSON: attempts per fault op.',
  backoff_s DOUBLE,
  latency_ms INT,
  policy_decision STRING,
  result_summary STRING COMMENT 'JSON with ids, counts and flags only.',
  session_id_hash STRING,
  customer_key STRING COMMENT 'HMAC of the customer id: links records without storing the id.',
  auth_method STRING,
  security_events STRING,
  faults_injected STRING,
  warnings STRING,
  env STRING,
  repository STRING,
  service_version STRING,
  policy_version STRING
) CLUSTER BY (recorded_date)
COMMENT 'One redacted record per bank tool call. Retention 90 days.';
